schema_version: 1

context:
  version: 6.8.3
  mbedtls_version: 3.*

package:
  name: qt6-opcua
  version: ${{ version }}

source:
  git: https://github.com/qt/qtopcua
  tag: v${{ version }}

build:
  number: 0
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - qt6-main ${{ version }}.*
        - mbedtls ${{ mbedtls_version }}
    - cmake
    - ninja
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - qt6-main ${{ version }}.*
    - mbedtls ${{ mbedtls_version }}
  run:
    - qt6-main ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage('qt6-opcua', upper_bound='x.x') }}
tests:
  - script:
      - if: win
        then: 
          - if not exist %LIBRARY_LIB%\\qt6\\bin\\Qt6OpcUa.dll exit 1
          - if not exist %LIBRARY_BIN%\\Qt6OpcUa.dll exit 1

about:
  summary: Qt OPC UA module
  description: |
    The Qt OPC UA module implements a Qt API to interact 
    with OPC UA servers on top of the open62541 library.
  license: LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
  license_file: LICENSES/
  documentation: https://doc.qt.io/qt-6/qtopcua-index.html
  repository: https://github.com/qt/qtopcua