schema_version: 1

context:
  version: 6.8.3
  mbedtls_version: 3.*

package:
  name: qt6-opcua
  version: ${{ version }}

source:
  git: https://github.com/qt/qtopcua
  tag: v${{ version }}

build:
  number: 0
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - qt6-main ${{ version }}.*
        - mbedtls ${{ mbedtls_version }}
    - cmake
    - ninja
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - qt6-main ${{ version }}.*
    - mbedtls ${{ mbedtls_version }}
  run:
    - qt6-main ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage('qt6-opcua', upper_bound='x.x') }}
tests:
  - script:
      - if: win
        then: 
          - if not exist %LIBRARY_LIB%\\qt6\\bin\\Qt6OpcUa.dll exit 1
          - if not exist %LIBRARY_BIN%\\Qt6OpcUa.dll exit 1

about:
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  summary: Qt6 OpcUa Libraries
